package entity;
// Generated 2017-10-30 19:23:51 by Hibernate Tools 5.2.3.Final

/**
 * Rooms generated by hbm2java
 */
public class Rooms implements java.io.Serializable {

	private int roomid;
	private String roomname;
	private String roomdesc;
	private String roomtype;
	private float roomprice;
	private Screenings screenings;

	public Rooms() {
	}

	public Rooms(int roomid, String roomname, String roomdesc, String roomtype, float roomprice) {
		this.roomid = roomid;
		this.roomname = roomname;
		this.roomdesc = roomdesc;
		this.roomtype = roomtype;
		this.roomprice = roomprice;
	}

	public Rooms(int roomid, String roomname, String roomdesc, String roomtype, float roomprice,
			Screenings screenings) {
		this.roomid = roomid;
		this.roomname = roomname;
		this.roomdesc = roomdesc;
		this.roomtype = roomtype;
		this.roomprice = roomprice;
		this.screenings = screenings;
	}

	public int getRoomid() {
		return this.roomid;
	}

	public void setRoomid(int roomid) {
		this.roomid = roomid;
	}

	public String getRoomname() {
		return this.roomname;
	}

	public void setRoomname(String roomname) {
		this.roomname = roomname;
	}

	public String getRoomdesc() {
		return this.roomdesc;
	}

	public void setRoomdesc(String roomdesc) {
		this.roomdesc = roomdesc;
	}

	public String getRoomtype() {
		return this.roomtype;
	}

	public void setRoomtype(String roomtype) {
		this.roomtype = roomtype;
	}

	public float getRoomprice() {
		return this.roomprice;
	}

	public void setRoomprice(float roomprice) {
		this.roomprice = roomprice;
	}

	public Screenings getScreenings() {
		return this.screenings;
	}

	public void setScreenings(Screenings screenings) {
		this.screenings = screenings;
	}

}
