package entity;
// Generated 2017-11-6 15:33:08 by Hibernate Tools 5.2.3.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Screenings generated by hbm2java
 */
public class Screenings implements java.io.Serializable {

	private Integer scid;
	private Date starttime;
	private Date overtime;
	private Date scdate;
	private Set orderses = new HashSet(0);

	public Screenings() {
	}

	public Screenings(Date starttime, Date overtime, Date scdate) {
		this.starttime = starttime;
		this.overtime = overtime;
		this.scdate = scdate;
	}

	public Screenings(Date starttime, Date overtime, Date scdate, Set orderses) {
		this.starttime = starttime;
		this.overtime = overtime;
		this.scdate = scdate;
		this.orderses = orderses;
	}

	public Integer getScid() {
		return this.scid;
	}

	public void setScid(Integer scid) {
		this.scid = scid;
	}

	public Date getStarttime() {
		return this.starttime;
	}

	public void setStarttime(Date starttime) {
		this.starttime = starttime;
	}

	public Date getOvertime() {
		return this.overtime;
	}

	public void setOvertime(Date overtime) {
		this.overtime = overtime;
	}

	public Date getScdate() {
		return this.scdate;
	}

	public void setScdate(Date scdate) {
		this.scdate = scdate;
	}

	public Set getOrderses() {
		return this.orderses;
	}

	public void setOrderses(Set orderses) {
		this.orderses = orderses;
	}

}
