package entity;
// Generated 2017-10-30 19:23:51 by Hibernate Tools 5.2.3.Final

import java.math.BigInteger;
import java.security.MessageDigest;
import java.util.HashSet;
import java.util.Set;

/**
 * Users generated by hbm2java
 */
public class Users implements java.io.Serializable {

	private int userid;
	private String username;
	private String userpasswd;
	private String sex;
	private int age;
	private String useremail;
	private String userimg;
	private String userphone;
	private Set orderses = new HashSet(0);

	public Users() {
	}

	public Users(int userid, String username, String userpasswd, String sex, int age, String useremail, String userimg,
			String userphone) {
		this.userid = userid;
		this.username = username;
		this.userpasswd = userpasswd;
		this.sex = sex;
		this.age = age;
		this.useremail = useremail;
		this.userimg = userimg;
		this.userphone = userphone;
	}

	public Users(int userid, String username, String userpasswd, String sex, int age, String useremail, String userimg,
			String userphone, Set orderses) {
		this.userid = userid;
		this.username = username;
		this.userpasswd = userpasswd;
		this.sex = sex;
		this.age = age;
		this.useremail = useremail;
		this.userimg = userimg;
		this.userphone = userphone;
		this.orderses = orderses;
	}

	public int getUserid() {
		return userid;
	}

	public void setUserid(int userid) {
		this.userid = userid;
	}

	public String getUsername() {
		return username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getUserpasswd() {
		return userpasswd;
	}

	public void setUserpasswd(String userpasswd) {
		
		this.userpasswd = userpasswd;
		
	}

	public String getSex() {
		return sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}

	public int getAge() {
		return age;
	}

	public void setAge(int age) {
		this.age = age;
	}

	public String getUseremail() {
		return useremail;
	}

	public void setUseremail(String useremail) {
		this.useremail = useremail;
	}

	public String getUserimg() {
		return userimg;
	}

	public void setUserimg(String userimg) {
		this.userimg = userimg;
	}

	public String getUserphone() {
		return userphone;
	}

	public void setUserphone(String userphone) {
		this.userphone = userphone;
	}

	public Set getOrderses() {
		return orderses;
	}

	public void setOrderses(Set orderses) {
		this.orderses = orderses;
	}


}
