package entity;
// Generated 2017-10-30 19:23:51 by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Types generated by hbm2java
 */
public class Types implements java.io.Serializable {
	private int typeid;
	private String typename;
	private Set movieses = new HashSet(0);

	public Types() {
	}

	public Types(int typeid, String typename) {
		this.typeid = typeid;
		this.typename = typename;
	}

	public Types(int typeid, String typename, Set movieses) {
		this.typeid = typeid;
		this.typename = typename;
		this.movieses = movieses;
	}

	public int getTypeid() {
		return this.typeid;
	}

	public void setTypeid(int typeid) {
		this.typeid = typeid;
	}

	public String getTypename() {
		return this.typename;
	}

	public void setTypename(String typename) {
		this.typename = typename;
	}

	public Set getMovieses() {
		return this.movieses;
	}

	public void setMovieses(Set movieses) {
		this.movieses = movieses;
	}

}
