package entity;
// Generated 2017-10-30 19:23:51 by Hibernate Tools 5.2.3.Final

/**
 * Lunbo generated by hbm2java
 */
public class Lunbo implements java.io.Serializable {

	private int srcid;
	private String srcs;

	public Lunbo() {
	}

	public Lunbo(int srcid, String srcs) {
		this.srcid = srcid;
		this.srcs = srcs;
	}

	public int getSrcid() {
		return this.srcid;
	}

	public void setSrcid(int srcid) {
		this.srcid = srcid;
	}

	public String getSrcs() {
		return this.srcs;
	}

	public void setSrcs(String srcs) {
		this.srcs = srcs;
	}

}
