package entity;
// Generated 2017-11-6 15:33:08 by Hibernate Tools 5.2.3.Final

import java.util.Date;

/**
 * Orders generated by hbm2java
 */
public class Orders implements java.io.Serializable {

	private Integer orderno;
	private Movies movies;
	private Rooms rooms;
	private Screenings screenings;
	private Users users;
	private Date reconfirmtime;
	private float cost;
	private Date scheduledtime;

	public Orders() {
	}

	public Orders(Movies movies, Rooms rooms, Screenings screenings, Users users, Date reconfirmtime, float cost,
			Date scheduledtime) {
		this.movies = movies;
		this.rooms = rooms;
		this.screenings = screenings;
		this.users = users;
		this.reconfirmtime = reconfirmtime;
		this.cost = cost;
		this.scheduledtime = scheduledtime;
	}

	public Integer getOrderno() {
		return this.orderno;
	}

	public void setOrderno(Integer orderno) {
		this.orderno = orderno;
	}

	public Movies getMovies() {
		return this.movies;
	}

	public void setMovies(Movies movies) {
		this.movies = movies;
	}

	public Rooms getRooms() {
		return this.rooms;
	}

	public void setRooms(Rooms rooms) {
		this.rooms = rooms;
	}

	public Screenings getScreenings() {
		return this.screenings;
	}

	public void setScreenings(Screenings screenings) {
		this.screenings = screenings;
	}

	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	public Date getReconfirmtime() {
		return this.reconfirmtime;
	}

	public void setReconfirmtime(Date reconfirmtime) {
		this.reconfirmtime = reconfirmtime;
	}

	public float getCost() {
		return this.cost;
	}

	public void setCost(float cost) {
		this.cost = cost;
	}

	public Date getScheduledtime() {
		return this.scheduledtime;
	}

	public void setScheduledtime(Date scheduledtime) {
		this.scheduledtime = scheduledtime;
	}

}
